name: API Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: docker login --username ${{ github.repository_owner }} --password ${{ secrets.GIT_PASSWORD }} ghcr.io

      - name: Build Docker image
        run: docker build ./back-end -t ghcr.io/${{ github.repository_owner }}/ml-app-api:latest

      - name: Push Docker image to registry
        run: docker push ghcr.io/${{ github.repository_owner }}/ml-app-api:latest